version: "3.7"

services: 
  postgres-container:
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_name
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: database_name
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - postgres-container
    depends_on: 
      - postgres-container

volumes:
  pgdata:
    driver: local
