version: "3.7"

services: 
  codestation_database:
    image: postgres
    container_name: codestation_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code_station
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: code_station
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - codestation_database
    depends_on: 
      - codestation_database

volumes:
  pgdata:
    driver: local
